#!/bin/sh

# Configure PATH so that we can access our scripts below
export PATH=$PATH:~/.cabal/bin:~/.xmonad/bin:~/.local/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
xmodmap ~/.xmodmap
setxkbmap -variant altgr-intl -option ctrl:nocaps

# Start a window compositor
picom -b

# Start a browser
firefox &

# Start Telegram
telegram-desktop &

# Start Discord
Discord &

# Start Slack
slack &

# Start email client
astroid &

# Start bluetooth connections
connect-known-bt & > /dev/null

# Configure displays
autorandr --change

# Set wallpaper
eval $(~/.fehbg)

# Update lockscreen images
multilockscreen -u ~/Pictures/wallpaper.png &

# Launch Notification Server
dunst &

# Launch lockscreen manager
xss-lock -l -- multilockscreen -l blur --off 600 &

# Fix stuff with keyctl
nix-shell -p keyutils --run "keyctl link @u @s"

# Start flameshot in background
flameshot &
